import "./globals.css";
import { Fuzzy_Bubbles } from "next/font/google";

const fuzzyBubbles = Fuzzy_Bubbles({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Education App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={fuzzyBubbles.className}>{children}</body>
		</html>
	);
}
